services:
  database:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root93@"
      - "POSTGRES_DB=db_users"
    ports:
      - 5432:5432
    volumes:
      - /pg-data:/var/lib/postgres/data
